# Generated by Django 2.2.7 on 2020-08-31 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_code', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=250)),
                ('landmark', models.CharField(blank=True, max_length=200, null=True)),
                ('mobile_number', models.CharField(max_length=15)),
            ],
        ),
    ]
