# Generated by Django 2.2.7 on 2020-08-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0004_auto_20200819_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender_mark',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
