# Generated by Django 2.2.7 on 2020-09-01 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0008_user_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
    ]
