# Generated by Django 2.2.7 on 2020-09-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0009_remove_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
