# Generated by Django 2.2.7 on 2020-09-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200908_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='colors',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sizes',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
